version: '3'

services:

  drone-network-dashboard:
    build: ./modules/dashboard
    image: dt-rush/drone-network-dashboard
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "drone-network-db" 
    env_file:
      - "config.env"
    volumes:
      - ./modules/dashboard:/code
      - ./modules/shared:/opt/lib/drone-network/shared

  drone-network-db:
    build: ./modules/db
    image: dt-rush/drone-network-db
    restart: always
    env_file:
      - "config.env"

  drone-network-net-ops-center:
    build: ./modules/net-ops-center
    image: dt-rush/drone-network-net-ops-center
    restart: always
    depends_on: 
      - "drone-network-db"
    env_file:
      - "config.env"
    volumes:
      - ./modules/net-ops-center:/code
      - ./modules/shared:/opt/lib/drone-network/shared

  drone-network-drone-sim:
    build: ./modules/drone-sim
    image: dt-rush/drone-network-drone-sim
    restart: always
    depends_on: 
      - "drone-network-net-ops-center"
    env_file:
      - "config.env"
    volumes:
      - ./modules/drone-sim:/code
      - ./modules/shared:/opt/lib/drone-network/shared

  
