version: '3'

services:

  drone-network-dashboard:
    build: ./modules/dashboard
    image: dt-rush/drone-network-dashboard
    restart: always
    environment:
      NODE_ENV: production
    volumes:
    - ./modules/dashboard:/code
    - ./modules/shared:/opt/lib/drone-network/shared

  drone-network-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dtrush 
      MONGO_INITDB_ROOT_PASSWORD: dtrush 

  drone-network-net-ops-center:
    build: ./modules/net-ops-center
    image: dt-rush/drone-network-net-ops-center
    restart: always
    environment:
      NODE_ENV: production
    volumes:
    - ./modules/net-ops-center:/code
    - ./modules/shared:/opt/lib/drone-network/shared

  drone-network-drone-sim:
    build: ./modules/drone-sim
    image: dt-rush/drone-network-drone-sim
    restart: always
    environment:
      NODE_ENV: production
    volumes:
    - ./modules/drone-sim:/code
    - ./modules/shared:/opt/lib/drone-network/shared

  
